#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-common

. /etc/nsm/securityonion-ag.conf

if [ "$ACNG_ENABLED" = "yes" ]; then
echo -n "so-acng: "
if docker ps | grep -q so-acng; then
                echo "Already started!"
        else
		docker rm so-acng >/dev/null 2>&1
#		docker run   --restart always   --detach  --volume /opt/airgap/acng/apt-cacher-ng-vol:/var/cache/apt-cacher-ng:rw --volume /etc/apt-cacher-ng/acng.conf:/etc/apt-cacher-ng/acng.conf:rw --publish 3142:3142   --name so-acng securityonionsolutions/acng


                docker run --name=so-acng \
                        --restart always \
                        --detach \
                        --volume /opt/airgap/acng/apt-cacher-ng-vol:/var/cache/apt-cacher-ng:rw \
                        --volume /etc/apt-cacher-ng:/etc/apt-cacher-ng:rw\
                        --publish 3142:3142 \
                        $ACNG_OPTIONS \
			securityonionsolutions/acng	
                #if [ "$ACNG_MASTER_NODE" = "yes" ]; then
                #        docker exec -it so-acng bash -c "sed -i -e 's/# Offlinemode: 0/Offlinemode: 1/g' /etc/apt-cacher-ng/acng.conf"
                #        docker stop so-acng
                #        docker start so-acng
                
        fi
fi
