#!/bin/bash

IMAGEDIR="/opt/airgap/load"

# Copy over Registry scripts and make them executable
cp -av registry/so-registry* /usr/sbin && chmod +x /usr/sbin/so-registry*
cp registry/so-docker-load /usr/sbin/so-docker-load && chmod +x /usr/sbin/so-docker-load 
cp etc/securityonion-ag.conf /etc/nsm/securityonion-ag.conf

# Run Registry install
/usr/sbin/so-registry-configure -y -n 
